@HOST = http://localhost:5000/api/
@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNWU1Y2MxNC04NjE1LTQwNGEtYmQxYS0xODA2MjM5ZjAxNDYiLCJ1c2VybmFtZSI6ImpvaG4xLmRvZSIsImlhdCI6MTc2MjA3NDM4NywiZXhwIjoxNzYyMDc3OTg3fQ.udsEvZHdgWloLxELTY-ikFc4Kwl_LLqDr4Og9k7Co34

### Health
GET {{HOST}}health

### Login
POST {{HOST}}auth/login
Content-Type: application/json

{
    "username": "john1.doe",
    "password": "passw0rd"
}

###
GET {{HOST}}auth/protected
Authorization: {{TOKEN}}